/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { Division } from '../models';
import { Divisions } from '../models';
/**
 * DivisionsApi - axios parameter creator
 * @export
 */
export const DivisionsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * You can use this to also retrieve inactive divisions. For example, the ID for the old Patrick division is `13`.
         * @summary Get an NHL division.
         * @param {number} id The ID of the division.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDivision: async (id: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling getDivision.');
            }
            const localVarPath = `/divisions/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * This only retrieves active divisions. For inactive divisions, use `/divisions/{id}`.
         * @summary Get all current NHL divisions.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDivisions: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/divisions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DivisionsApi - functional programming interface
 * @export
 */
export const DivisionsApiFp = function(configuration?: Configuration) {
    return {
        /**
         * You can use this to also retrieve inactive divisions. For example, the ID for the old Patrick division is `13`.
         * @summary Get an NHL division.
         * @param {number} id The ID of the division.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDivision(id: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Division>> {
            const localVarAxiosArgs = await DivisionsApiAxiosParamCreator(configuration).getDivision(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * This only retrieves active divisions. For inactive divisions, use `/divisions/{id}`.
         * @summary Get all current NHL divisions.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDivisions(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Divisions>> {
            const localVarAxiosArgs = await DivisionsApiAxiosParamCreator(configuration).getDivisions(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * DivisionsApi - factory interface
 * @export
 */
export const DivisionsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * You can use this to also retrieve inactive divisions. For example, the ID for the old Patrick division is `13`.
         * @summary Get an NHL division.
         * @param {number} id The ID of the division.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDivision(id: number, options?: any): AxiosPromise<Division> {
            return DivisionsApiFp(configuration).getDivision(id, options).then((request) => request(axios, basePath));
        },
        /**
         * This only retrieves active divisions. For inactive divisions, use `/divisions/{id}`.
         * @summary Get all current NHL divisions.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDivisions(options?: any): AxiosPromise<Divisions> {
            return DivisionsApiFp(configuration).getDivisions(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DivisionsApi - object-oriented interface
 * @export
 * @class DivisionsApi
 * @extends {BaseAPI}
 */
export class DivisionsApi extends BaseAPI {
    /**
     * You can use this to also retrieve inactive divisions. For example, the ID for the old Patrick division is `13`.
     * @summary Get an NHL division.
     * @param {number} id The ID of the division.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DivisionsApi
     */
    public getDivision(id: number, options?: any) {
        return DivisionsApiFp(this.configuration).getDivision(id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * This only retrieves active divisions. For inactive divisions, use `/divisions/{id}`.
     * @summary Get all current NHL divisions.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DivisionsApi
     */
    public getDivisions(options?: any) {
        return DivisionsApiFp(this.configuration).getDivisions(options).then((request) => request(this.axios, this.basePath));
    }
}
