/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { Draft } from '../models';
import { DraftProspects } from '../models';
/**
 * DraftApi - axios parameter creator
 * @export
 */
export const DraftApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get round-by-round data for current year's NHL Entry Draft.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDraft: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/draft`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get round-by-round data for a specific year's NHL Entry Draft.
         * @param {number} year The draft year.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDraftByYear: async (year: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'year' is not null or undefined
            if (year === null || year === undefined) {
                throw new RequiredError('year','Required parameter year was null or undefined when calling getDraftByYear.');
            }
            const localVarPath = `/draft/{year}`
                .replace(`{${"year"}}`, encodeURIComponent(String(year)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get an NHL Entry Draft prospect.
         * @param {number} id The prospect ID.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDraftProspect: async (id: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling getDraftProspect.');
            }
            const localVarPath = `/draft/prospects/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Be forewarned that this endpoint returns a **lot** of data and there does not appear to be a way to paginate results.
         * @summary Get all NHL Entry Draft prospects.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDraftProspects: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/draft/prospects`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DraftApi - functional programming interface
 * @export
 */
export const DraftApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get round-by-round data for current year's NHL Entry Draft.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDraft(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Draft>> {
            const localVarAxiosArgs = await DraftApiAxiosParamCreator(configuration).getDraft(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Get round-by-round data for a specific year's NHL Entry Draft.
         * @param {number} year The draft year.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDraftByYear(year: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Draft>> {
            const localVarAxiosArgs = await DraftApiAxiosParamCreator(configuration).getDraftByYear(year, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Get an NHL Entry Draft prospect.
         * @param {number} id The prospect ID.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDraftProspect(id: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DraftProspects>> {
            const localVarAxiosArgs = await DraftApiAxiosParamCreator(configuration).getDraftProspect(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Be forewarned that this endpoint returns a **lot** of data and there does not appear to be a way to paginate results.
         * @summary Get all NHL Entry Draft prospects.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDraftProspects(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DraftProspects>> {
            const localVarAxiosArgs = await DraftApiAxiosParamCreator(configuration).getDraftProspects(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * DraftApi - factory interface
 * @export
 */
export const DraftApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Get round-by-round data for current year's NHL Entry Draft.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDraft(options?: any): AxiosPromise<Draft> {
            return DraftApiFp(configuration).getDraft(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get round-by-round data for a specific year's NHL Entry Draft.
         * @param {number} year The draft year.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDraftByYear(year: number, options?: any): AxiosPromise<Draft> {
            return DraftApiFp(configuration).getDraftByYear(year, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get an NHL Entry Draft prospect.
         * @param {number} id The prospect ID.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDraftProspect(id: number, options?: any): AxiosPromise<DraftProspects> {
            return DraftApiFp(configuration).getDraftProspect(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Be forewarned that this endpoint returns a **lot** of data and there does not appear to be a way to paginate results.
         * @summary Get all NHL Entry Draft prospects.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDraftProspects(options?: any): AxiosPromise<DraftProspects> {
            return DraftApiFp(configuration).getDraftProspects(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DraftApi - object-oriented interface
 * @export
 * @class DraftApi
 * @extends {BaseAPI}
 */
export class DraftApi extends BaseAPI {
    /**
     * 
     * @summary Get round-by-round data for current year's NHL Entry Draft.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DraftApi
     */
    public getDraft(options?: any) {
        return DraftApiFp(this.configuration).getDraft(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Get round-by-round data for a specific year's NHL Entry Draft.
     * @param {number} year The draft year.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DraftApi
     */
    public getDraftByYear(year: number, options?: any) {
        return DraftApiFp(this.configuration).getDraftByYear(year, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Get an NHL Entry Draft prospect.
     * @param {number} id The prospect ID.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DraftApi
     */
    public getDraftProspect(id: number, options?: any) {
        return DraftApiFp(this.configuration).getDraftProspect(id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Be forewarned that this endpoint returns a **lot** of data and there does not appear to be a way to paginate results.
     * @summary Get all NHL Entry Draft prospects.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DraftApi
     */
    public getDraftProspects(options?: any) {
        return DraftApiFp(this.configuration).getDraftProspects(options).then((request) => request(this.axios, this.basePath));
    }
}
