/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Conference
 */
export interface Conference {
    /**
     * 
     * @type {number}
     * @memberof Conference
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof Conference
     */
    name?: ConferenceNameEnum;
    /**
     * 
     * @type {string}
     * @memberof Conference
     */
    link?: any;
    /**
     * 
     * @type {string}
     * @memberof Conference
     */
    abbreviation?: ConferenceAbbreviationEnum;
    /**
     * 
     * @type {string}
     * @memberof Conference
     */
    shortName?: ConferenceShortNameEnum;
    /**
     * 
     * @type {boolean}
     * @memberof Conference
     */
    active?: any;
}

/**
    * @export
    * @enum {string}
    */
export enum ConferenceNameEnum {
    Eastern = 'Eastern',
    Western = 'Western',
    WorldCupOfHockey = 'World Cup of Hockey'
}
/**
    * @export
    * @enum {string}
    */
export enum ConferenceAbbreviationEnum {
    E = 'E',
    W = 'W',
    WCH = 'WCH'
}
/**
    * @export
    * @enum {string}
    */
export enum ConferenceShortNameEnum {
    East = 'East',
    West = 'West',
    WCup = 'WCup'
}

