/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface DraftProspects
 */
export interface DraftProspects {
    /**
     * 
     * @type {string}
     * @memberof DraftProspects
     */
    copyright?: any;
    /**
     * 
     * @type {Array&lt;DraftProspect&gt;}
     * @memberof DraftProspects
     */
    prospects?: any;
}
