/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface DraftRounds
 */
export interface DraftRounds {
    /**
     * 
     * @type {number}
     * @memberof DraftRounds
     */
    roundNumber?: any;
    /**
     * 
     * @type {number}
     * @memberof DraftRounds
     */
    round?: any;
    /**
     * 
     * @type {Array&lt;DraftPicks&gt;}
     * @memberof DraftRounds
     */
    picks?: any;
}
