/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface GameBoxscoreTeamTeamStatsTeamSkaterStats
 */
export interface GameBoxscoreTeamTeamStatsTeamSkaterStats {
    /**
     * 
     * @type {number}
     * @memberof GameBoxscoreTeamTeamStatsTeamSkaterStats
     */
    goals?: any;
    /**
     * 
     * @type {number}
     * @memberof GameBoxscoreTeamTeamStatsTeamSkaterStats
     */
    pim?: any;
    /**
     * 
     * @type {number}
     * @memberof GameBoxscoreTeamTeamStatsTeamSkaterStats
     */
    shots?: any;
    /**
     * 
     * @type {string}
     * @memberof GameBoxscoreTeamTeamStatsTeamSkaterStats
     */
    powerPlayPercentage?: any;
    /**
     * 
     * @type {number}
     * @memberof GameBoxscoreTeamTeamStatsTeamSkaterStats
     */
    powerPlayGoals?: any;
    /**
     * 
     * @type {number}
     * @memberof GameBoxscoreTeamTeamStatsTeamSkaterStats
     */
    powerPlayOpportunities?: any;
    /**
     * 
     * @type {string}
     * @memberof GameBoxscoreTeamTeamStatsTeamSkaterStats
     */
    faceOffWinPercentage?: any;
    /**
     * 
     * @type {number}
     * @memberof GameBoxscoreTeamTeamStatsTeamSkaterStats
     */
    blocked?: any;
    /**
     * 
     * @type {number}
     * @memberof GameBoxscoreTeamTeamStatsTeamSkaterStats
     */
    takeaways?: any;
    /**
     * 
     * @type {number}
     * @memberof GameBoxscoreTeamTeamStatsTeamSkaterStats
     */
    giveaways?: any;
    /**
     * 
     * @type {number}
     * @memberof GameBoxscoreTeamTeamStatsTeamSkaterStats
     */
    hits?: any;
}
