/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface GameGameData
 */
export interface GameGameData {
    /**
     * 
     * @type {GameGameDataGame}
     * @memberof GameGameData
     */
    game?: any;
    /**
     * 
     * @type {GameGameDataDatetime}
     * @memberof GameGameData
     */
    datetime?: any;
    /**
     * 
     * @type {GameGameDataStatus}
     * @memberof GameGameData
     */
    status?: any;
    /**
     * 
     * @type {GameGameDataTeams}
     * @memberof GameGameData
     */
    teams?: any;
    /**
     * 
     * @type {Player}
     * @memberof GameGameData
     */
    players?: any;
    /**
     * 
     * @type {GameGameDataVenue}
     * @memberof GameGameData
     */
    venue?: any;
}
