/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface GameLiveDataPlaysPlaysByPeriod
 */
export interface GameLiveDataPlaysPlaysByPeriod {
    /**
     * 
     * @type {number}
     * @memberof GameLiveDataPlaysPlaysByPeriod
     */
    startIndex?: any;
    /**
     * 
     * @type {Array&lt;number&gt;}
     * @memberof GameLiveDataPlaysPlaysByPeriod
     */
    plays?: any;
    /**
     * 
     * @type {number}
     * @memberof GameLiveDataPlaysPlaysByPeriod
     */
    endIndex?: any;
}
