/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface GameEditorial
 */
export interface GameEditorial {
    /**
     * 
     * @type {string}
     * @memberof GameEditorial
     */
    type?: any;
    /**
     * 
     * @type {string}
     * @memberof GameEditorial
     */
    state?: any;
    /**
     * 
     * @type {Date}
     * @memberof GameEditorial
     */
    date?: any;
    /**
     * 
     * @type {string}
     * @memberof GameEditorial
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof GameEditorial
     */
    headline?: any;
    /**
     * 
     * @type {string}
     * @memberof GameEditorial
     */
    subhead?: any;
    /**
     * 
     * @type {string}
     * @memberof GameEditorial
     */
    seoTitle?: any;
    /**
     * 
     * @type {string}
     * @memberof GameEditorial
     */
    seoDescription?: any;
    /**
     * 
     * @type {string}
     * @memberof GameEditorial
     */
    seoKeywords?: any;
    /**
     * 
     * @type {string}
     * @memberof GameEditorial
     */
    slug?: any;
    /**
     * 
     * @type {boolean}
     * @memberof GameEditorial
     */
    commenting?: any;
    /**
     * 
     * @type {string}
     * @memberof GameEditorial
     */
    tagline?: any;
    /**
     * 
     * @type {GameEditorialTokenData}
     * @memberof GameEditorial
     */
    tokenData?: any;
    /**
     * 
     * @type {GameEditorialContributor}
     * @memberof GameEditorial
     */
    contributor?: any;
    /**
     * 
     * @type {Array&lt;GameEditorialKeyword&gt;}
     * @memberof GameEditorial
     */
    keywordsDisplay?: any;
    /**
     * 
     * @type {Array&lt;GameEditorialKeyword&gt;}
     * @memberof GameEditorial
     */
    keywordsAll?: any;
    /**
     * 
     * @type {string}
     * @memberof GameEditorial
     */
    approval?: any;
    /**
     * 
     * @type {string}
     * @memberof GameEditorial
     */
    url?: any;
    /**
     * 
     * @type {string}
     * @memberof GameEditorial
     */
    dataURI?: any;
    /**
     * 
     * @type {GameEditorialKeyword}
     * @memberof GameEditorial
     */
    primaryKeyword?: any;
    /**
     * 
     * @type {GameEditorialMedia}
     * @memberof GameEditorial
     */
    media?: any;
    /**
     * 
     * @type {string}
     * @memberof GameEditorial
     */
    preview?: any;
}
