/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface GameMediaAudioItems
 */
export interface GameMediaAudioItems {
    /**
     * 
     * @type {string}
     * @memberof GameMediaAudioItems
     */
    mediaState?: any;
    /**
     * 
     * @type {string}
     * @memberof GameMediaAudioItems
     */
    mediaPlaybackId?: any;
    /**
     * 
     * @type {string}
     * @memberof GameMediaAudioItems
     */
    mediaFeedType?: any;
    /**
     * 
     * @type {string}
     * @memberof GameMediaAudioItems
     */
    callLetters?: any;
    /**
     * 
     * @type {string}
     * @memberof GameMediaAudioItems
     */
    eventId?: any;
    /**
     * 
     * @type {string}
     * @memberof GameMediaAudioItems
     */
    language?: any;
    /**
     * 
     * @type {boolean}
     * @memberof GameMediaAudioItems
     */
    freeGame?: any;
    /**
     * 
     * @type {string}
     * @memberof GameMediaAudioItems
     */
    feedName?: any;
    /**
     * 
     * @type {boolean}
     * @memberof GameMediaAudioItems
     */
    gamePlus?: any;
}
