/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface GameBoxscoreTeamPlayers
 */
export interface GameBoxscoreTeamPlayers {
    /**
     * 
     * @type {GameBoxscoreTeamPlayersPerson}
     * @memberof GameBoxscoreTeamPlayers
     */
    person?: any;
    /**
     * 
     * @type {string}
     * @memberof GameBoxscoreTeamPlayers
     */
    jerseyNumber?: any;
    /**
     * 
     * @type {GameBoxscoreTeamPlayersPosition}
     * @memberof GameBoxscoreTeamPlayers
     */
    position?: any;
    /**
     * 
     * @type {GameBoxscoreTeamPlayersStats}
     * @memberof GameBoxscoreTeamPlayers
     */
    stats?: any;
}
