/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface GameLiveDataDecisions
 */
export interface GameLiveDataDecisions {
    /**
     * 
     * @type {GameDecisionPlayer}
     * @memberof GameLiveDataDecisions
     */
    winner?: any;
    /**
     * 
     * @type {GameDecisionPlayer}
     * @memberof GameLiveDataDecisions
     */
    loser?: any;
    /**
     * 
     * @type {GameDecisionPlayer}
     * @memberof GameLiveDataDecisions
     */
    firstStar?: any;
    /**
     * 
     * @type {GameDecisionPlayer}
     * @memberof GameLiveDataDecisions
     */
    secondStar?: any;
    /**
     * 
     * @type {GameDecisionPlayer}
     * @memberof GameLiveDataDecisions
     */
    thirdStar?: any;
}
