/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface GameLiveData
 */
export interface GameLiveData {
    /**
     * 
     * @type {GameLiveDataPlays}
     * @memberof GameLiveData
     */
    plays?: any;
    /**
     * 
     * @type {GameLinescore}
     * @memberof GameLiveData
     */
    linescore?: any;
    /**
     * 
     * @type {GameBoxscore}
     * @memberof GameLiveData
     */
    boxscore?: any;
    /**
     * 
     * @type {GameLiveDataDecisions}
     * @memberof GameLiveData
     */
    decisions?: any;
}
