/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Game
 */
export interface Game {
    /**
     * 
     * @type {string}
     * @memberof Game
     */
    copyright?: any;
    /**
     * 
     * @type {number}
     * @memberof Game
     */
    gamePk?: any;
    /**
     * 
     * @type {string}
     * @memberof Game
     */
    link?: any;
    /**
     * 
     * @type {GameMetaData}
     * @memberof Game
     */
    metaData?: any;
    /**
     * 
     * @type {GameGameData}
     * @memberof Game
     */
    gameData?: any;
    /**
     * 
     * @type {GameLiveData}
     * @memberof Game
     */
    liveData?: any;
}
