/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface GameContent
 */
export interface GameContent {
    /**
     * 
     * @type {string}
     * @memberof GameContent
     */
    copyright?: any;
    /**
     * 
     * @type {string}
     * @memberof GameContent
     */
    link?: any;
    /**
     * 
     * @type {GameContentEditorial}
     * @memberof GameContent
     */
    editorial?: any;
    /**
     * 
     * @type {GameContentMedia}
     * @memberof GameContent
     */
    media?: any;
    /**
     * 
     * @type {GameContentHighlights}
     * @memberof GameContent
     */
    highlights?: any;
}
