/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface GameBoxscores
 */
export interface GameBoxscores {
    /**
     * 
     * @type {GameBoxscoreTeams}
     * @memberof GameBoxscores
     */
    teams?: ;
    /**
     * 
     * @type {Array&lt;GameOfficial&gt;}
     * @memberof GameBoxscores
     */
    officials?: ;
}
