/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface GameHighlight
 */
export interface GameHighlight {
    /**
     * 
     * @type {string}
     * @memberof GameHighlight
     */
    type?: GameHighlightTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof GameHighlight
     */
    id?: any;
    /**
     * 
     * @type {Date}
     * @memberof GameHighlight
     */
    date?: any;
    /**
     * 
     * @type {string}
     * @memberof GameHighlight
     */
    title?: any;
    /**
     * 
     * @type {string}
     * @memberof GameHighlight
     */
    blurb?: any;
    /**
     * 
     * @type {string}
     * @memberof GameHighlight
     */
    description?: any;
    /**
     * 
     * @type {string}
     * @memberof GameHighlight
     */
    duration?: any;
    /**
     * 
     * @type {boolean}
     * @memberof GameHighlight
     */
    authFlow?: any;
    /**
     * 
     * @type {string}
     * @memberof GameHighlight
     */
    mediaPlaybackId?: any;
    /**
     * 
     * @type {string}
     * @memberof GameHighlight
     */
    mediaState?: any;
    /**
     * 
     * @type {Array&lt;GameEditorialKeyword&gt;}
     * @memberof GameHighlight
     */
    keywords?: any;
    /**
     * 
     * @type {Photo}
     * @memberof GameHighlight
     */
    image?: any;
    /**
     * 
     * @type {Array&lt;GameHighlightPlaybacks&gt;}
     * @memberof GameHighlight
     */
    playbacks?: any;
}

/**
    * @export
    * @enum {string}
    */
export enum GameHighlightTypeEnum {
    Video = 'video'
}

