/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface GameBoxscoreTeamPlayersStatsSkaterStats
 */
export interface GameBoxscoreTeamPlayersStatsSkaterStats {
    /**
     * 
     * @type {string}
     * @memberof GameBoxscoreTeamPlayersStatsSkaterStats
     */
    timeOnIce?: any;
    /**
     * 
     * @type {number}
     * @memberof GameBoxscoreTeamPlayersStatsSkaterStats
     */
    assists?: any;
    /**
     * 
     * @type {number}
     * @memberof GameBoxscoreTeamPlayersStatsSkaterStats
     */
    goals?: any;
    /**
     * 
     * @type {number}
     * @memberof GameBoxscoreTeamPlayersStatsSkaterStats
     */
    shots?: any;
    /**
     * 
     * @type {number}
     * @memberof GameBoxscoreTeamPlayersStatsSkaterStats
     */
    hits?: any;
    /**
     * 
     * @type {number}
     * @memberof GameBoxscoreTeamPlayersStatsSkaterStats
     */
    powerPlayGoals?: any;
    /**
     * 
     * @type {number}
     * @memberof GameBoxscoreTeamPlayersStatsSkaterStats
     */
    powerPlayAssists?: any;
    /**
     * 
     * @type {number}
     * @memberof GameBoxscoreTeamPlayersStatsSkaterStats
     */
    penaltyMinutes?: any;
    /**
     * 
     * @type {number}
     * @memberof GameBoxscoreTeamPlayersStatsSkaterStats
     */
    faceOffWins?: any;
    /**
     * 
     * @type {number}
     * @memberof GameBoxscoreTeamPlayersStatsSkaterStats
     */
    faceoffTaken?: any;
    /**
     * 
     * @type {number}
     * @memberof GameBoxscoreTeamPlayersStatsSkaterStats
     */
    takeaways?: any;
    /**
     * 
     * @type {number}
     * @memberof GameBoxscoreTeamPlayersStatsSkaterStats
     */
    giveaways?: any;
    /**
     * 
     * @type {number}
     * @memberof GameBoxscoreTeamPlayersStatsSkaterStats
     */
    shortHandedGoals?: any;
    /**
     * 
     * @type {number}
     * @memberof GameBoxscoreTeamPlayersStatsSkaterStats
     */
    shortHandedAssists?: any;
    /**
     * 
     * @type {number}
     * @memberof GameBoxscoreTeamPlayersStatsSkaterStats
     */
    blocked?: any;
    /**
     * 
     * @type {number}
     * @memberof GameBoxscoreTeamPlayersStatsSkaterStats
     */
    plusMinus?: any;
    /**
     * 
     * @type {string}
     * @memberof GameBoxscoreTeamPlayersStatsSkaterStats
     */
    evenTimeOnIce?: any;
    /**
     * 
     * @type {string}
     * @memberof GameBoxscoreTeamPlayersStatsSkaterStats
     */
    powerPlayTimeOnIce?: any;
    /**
     * 
     * @type {string}
     * @memberof GameBoxscoreTeamPlayersStatsSkaterStats
     */
    shortHandedTimeOnIce?: any;
}
