/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface GameLinescoreTeam
 */
export interface GameLinescoreTeam {
    /**
     * 
     * @type {GameBoxscoreTeamTeam}
     * @memberof GameLinescoreTeam
     */
    team?: any;
    /**
     * 
     * @type {number}
     * @memberof GameLinescoreTeam
     */
    goals?: any;
    /**
     * 
     * @type {number}
     * @memberof GameLinescoreTeam
     */
    shotsOnGoal?: any;
    /**
     * 
     * @type {boolean}
     * @memberof GameLinescoreTeam
     */
    goaliePulled?: any;
    /**
     * 
     * @type {number}
     * @memberof GameLinescoreTeam
     */
    numSkaters?: any;
    /**
     * 
     * @type {boolean}
     * @memberof GameLinescoreTeam
     */
    powerPlay?: any;
}
