/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface GameEditorialTokenData
 */
export interface GameEditorialTokenData {
    /**
     * 
     * @type {string}
     * @memberof GameEditorialTokenData
     */
    tokenGUID?: any;
    /**
     * 
     * @type {string}
     * @memberof GameEditorialTokenData
     */
    type?: GameEditorialTokenDataTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof GameEditorialTokenData
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof GameEditorialTokenData
     */
    teamId?: any;
    /**
     * 
     * @type {string}
     * @memberof GameEditorialTokenData
     */
    name?: any;
    /**
     * 
     * @type {string}
     * @memberof GameEditorialTokenData
     */
    seoName?: any;
    /**
     * 
     * @type {string}
     * @memberof GameEditorialTokenData
     */
    href?: any;
    /**
     * 
     * @type {string}
     * @memberof GameEditorialTokenData
     */
    hrefMobile?: any;
}

/**
    * @export
    * @enum {string}
    */
export enum GameEditorialTokenDataTypeEnum {
    HyperLink = 'hyperLink',
    PlayerCard = 'playerCard'
}

