/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface GameLinescoreIntermissionInfo
 */
export interface GameLinescoreIntermissionInfo {
    /**
     * 
     * @type {number}
     * @memberof GameLinescoreIntermissionInfo
     */
    intermissionTimeRemaining?: any;
    /**
     * 
     * @type {number}
     * @memberof GameLinescoreIntermissionInfo
     */
    intermissionTimeElapsed?: any;
    /**
     * 
     * @type {boolean}
     * @memberof GameLinescoreIntermissionInfo
     */
    inIntermission?: any;
}
