/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface GameContentMediaMilestonesItems
 */
export interface GameContentMediaMilestonesItems {
    /**
     * 
     * @type {string}
     * @memberof GameContentMediaMilestonesItems
     */
    title?: any;
    /**
     * 
     * @type {string}
     * @memberof GameContentMediaMilestonesItems
     */
    description?: any;
    /**
     * 
     * @type {string}
     * @memberof GameContentMediaMilestonesItems
     */
    type?: GameContentMediaMilestonesItemsTypeEnum;
    /**
     * 
     * @type {Date}
     * @memberof GameContentMediaMilestonesItems
     */
    timeAbsolute?: any;
    /**
     * 
     * @type {string}
     * @memberof GameContentMediaMilestonesItems
     */
    timeOffset?: any;
    /**
     * 
     * @type {string}
     * @memberof GameContentMediaMilestonesItems
     */
    period?: any;
    /**
     * 
     * @type {string}
     * @memberof GameContentMediaMilestonesItems
     */
    statsEventId?: any;
    /**
     * 
     * @type {string}
     * @memberof GameContentMediaMilestonesItems
     */
    teamId?: any;
    /**
     * 
     * @type {string}
     * @memberof GameContentMediaMilestonesItems
     */
    playerId?: any;
    /**
     * 
     * @type {string}
     * @memberof GameContentMediaMilestonesItems
     */
    periodTime?: any;
    /**
     * 
     * @type {string}
     * @memberof GameContentMediaMilestonesItems
     */
    ordinalNum?: any;
    /**
     * 
     * @type {GameHighlight}
     * @memberof GameContentMediaMilestonesItems
     */
    highlight?: any;
}

/**
    * @export
    * @enum {string}
    */
export enum GameContentMediaMilestonesItemsTypeEnum {
    BROADCASTSTART = 'BROADCAST_START',
    BROADCASTEND = 'BROADCAST_END',
    GOAL = 'GOAL',
    PERIODEND = 'PERIOD_END',
    PERIODSTART = 'PERIOD_START',
    SHOT = 'SHOT'
}

