/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface GameGameDataStatus
 */
export interface GameGameDataStatus {
    /**
     * 
     * @type {string}
     * @memberof GameGameDataStatus
     */
    abstractGameState?: any;
    /**
     * 
     * @type {string}
     * @memberof GameGameDataStatus
     */
    codedGameState?: any;
    /**
     * 
     * @type {string}
     * @memberof GameGameDataStatus
     */
    detailedState?: any;
    /**
     * 
     * @type {string}
     * @memberof GameGameDataStatus
     */
    statusCode?: any;
    /**
     * 
     * @type {boolean}
     * @memberof GameGameDataStatus
     */
    startTimeTBD?: any;
}
