/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface PhotoCuts
 */
export interface PhotoCuts {
    /**
     * 
     * @type {string}
     * @memberof PhotoCuts
     */
    aspectRatio?: any;
    /**
     * 
     * @type {number}
     * @memberof PhotoCuts
     */
    width?: any;
    /**
     * 
     * @type {number}
     * @memberof PhotoCuts
     */
    height?: any;
    /**
     * 
     * @type {string}
     * @memberof PhotoCuts
     */
    src?: any;
    /**
     * 
     * @type {string}
     * @memberof PhotoCuts
     */
    at2x?: any;
    /**
     * 
     * @type {string}
     * @memberof PhotoCuts
     */
    at3x?: any;
}
