/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface PlayerStatsStat
 */
export interface PlayerStatsStat {
    /**
     * 
     * @type {string}
     * @memberof PlayerStatsStat
     */
    timeOnIce?: any;
    /**
     * 
     * @type {string}
     * @memberof PlayerStatsStat
     */
    assists?: any;
    /**
     * 
     * @type {number}
     * @memberof PlayerStatsStat
     */
    goals?: any;
    /**
     * 
     * @type {number}
     * @memberof PlayerStatsStat
     */
    pim?: any;
    /**
     * 
     * @type {number}
     * @memberof PlayerStatsStat
     */
    shots?: any;
    /**
     * 
     * @type {number}
     * @memberof PlayerStatsStat
     */
    games?: any;
    /**
     * 
     * @type {number}
     * @memberof PlayerStatsStat
     */
    hits?: any;
    /**
     * 
     * @type {number}
     * @memberof PlayerStatsStat
     */
    powerPlayGoals?: any;
    /**
     * 
     * @type {number}
     * @memberof PlayerStatsStat
     */
    powerPlayPoints?: any;
    /**
     * 
     * @type {number}
     * @memberof PlayerStatsStat
     */
    powerPlayTimeOnIce?: any;
    /**
     * 
     * @type {number}
     * @memberof PlayerStatsStat
     */
    evenTimeOnIce?: any;
    /**
     * 
     * @type {number}
     * @memberof PlayerStatsStat
     */
    penaltyMinutes?: any;
    /**
     * 
     * @type {number}
     * @memberof PlayerStatsStat
     */
    faceOffPct?: any;
    /**
     * 
     * @type {number}
     * @memberof PlayerStatsStat
     */
    shotPct?: any;
    /**
     * 
     * @type {number}
     * @memberof PlayerStatsStat
     */
    gameWinningGoals?: any;
    /**
     * 
     * @type {number}
     * @memberof PlayerStatsStat
     */
    overTimeGoals?: any;
    /**
     * 
     * @type {number}
     * @memberof PlayerStatsStat
     */
    shortHandedGoals?: any;
    /**
     * 
     * @type {number}
     * @memberof PlayerStatsStat
     */
    shortHandedPoints?: any;
    /**
     * 
     * @type {string}
     * @memberof PlayerStatsStat
     */
    shortHandedTimeOnIce?: any;
    /**
     * 
     * @type {number}
     * @memberof PlayerStatsStat
     */
    blocked?: any;
    /**
     * 
     * @type {number}
     * @memberof PlayerStatsStat
     */
    plusMinus?: any;
    /**
     * 
     * @type {number}
     * @memberof PlayerStatsStat
     */
    points?: any;
    /**
     * 
     * @type {number}
     * @memberof PlayerStatsStat
     */
    shifts?: any;
    /**
     * 
     * @type {string}
     * @memberof PlayerStatsStat
     */
    timeOnIcePerGame?: any;
    /**
     * 
     * @type {string}
     * @memberof PlayerStatsStat
     */
    evenTimeOnIcePerGame?: any;
    /**
     * 
     * @type {string}
     * @memberof PlayerStatsStat
     */
    shortHandedTimeOnIcePerGame?: any;
    /**
     * 
     * @type {string}
     * @memberof PlayerStatsStat
     */
    powerPlayTimeOnIcePerGame?: any;
    /**
     * 
     * @type {string}
     * @memberof PlayerStatsStat
     */
    rankPowerPlayGoals?: any;
    /**
     * 
     * @type {string}
     * @memberof PlayerStatsStat
     */
    rankBlockedShots?: any;
    /**
     * 
     * @type {string}
     * @memberof PlayerStatsStat
     */
    rankAssists?: any;
    /**
     * 
     * @type {string}
     * @memberof PlayerStatsStat
     */
    rankShotPct?: any;
    /**
     * 
     * @type {string}
     * @memberof PlayerStatsStat
     */
    rankGoals?: any;
    /**
     * 
     * @type {string}
     * @memberof PlayerStatsStat
     */
    rankHits?: any;
    /**
     * 
     * @type {string}
     * @memberof PlayerStatsStat
     */
    rankPenaltyMinutes?: any;
    /**
     * 
     * @type {string}
     * @memberof PlayerStatsStat
     */
    rankShortHandedGoals?: any;
    /**
     * 
     * @type {string}
     * @memberof PlayerStatsStat
     */
    rankPlusMinus?: any;
    /**
     * 
     * @type {string}
     * @memberof PlayerStatsStat
     */
    rankShots?: any;
    /**
     * 
     * @type {string}
     * @memberof PlayerStatsStat
     */
    rankPoints?: any;
    /**
     * 
     * @type {string}
     * @memberof PlayerStatsStat
     */
    rankOvertimeGoals?: any;
    /**
     * 
     * @type {string}
     * @memberof PlayerStatsStat
     */
    rankGamesPlayed?: any;
    /**
     * 
     * @type {number}
     * @memberof PlayerStatsStat
     */
    goalsInFirstPeriod?: any;
    /**
     * 
     * @type {number}
     * @memberof PlayerStatsStat
     */
    goalsInSecondPeriod?: any;
    /**
     * 
     * @type {number}
     * @memberof PlayerStatsStat
     */
    goalsInThirdPeriod?: any;
    /**
     * 
     * @type {number}
     * @memberof PlayerStatsStat
     */
    goalsTrailingByOne?: any;
    /**
     * 
     * @type {number}
     * @memberof PlayerStatsStat
     */
    goalsTrailingByTwo?: any;
    /**
     * 
     * @type {number}
     * @memberof PlayerStatsStat
     */
    goalsTrailingByThreePlus?: any;
    /**
     * 
     * @type {number}
     * @memberof PlayerStatsStat
     */
    goalsWhenTied?: any;
    /**
     * 
     * @type {number}
     * @memberof PlayerStatsStat
     */
    goalsLeadingByOne?: any;
    /**
     * 
     * @type {number}
     * @memberof PlayerStatsStat
     */
    goalsLeadingByTwo?: any;
}
