/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface PlayerStatsSplits
 */
export interface PlayerStatsSplits {
    /**
     * 
     * @type {string}
     * @memberof PlayerStatsSplits
     */
    season?: any;
    /**
     * 
     * @type {PlayerStatsStat}
     * @memberof PlayerStatsSplits
     */
    stat?: any;
    /**
     * 
     * @type {boolean}
     * @memberof PlayerStatsSplits
     */
    isHome?: any;
    /**
     * 
     * @type {boolean}
     * @memberof PlayerStatsSplits
     */
    isWin?: any;
    /**
     * 
     * @type {boolean}
     * @memberof PlayerStatsSplits
     */
    isOT?: any;
    /**
     * 
     * @type {number}
     * @memberof PlayerStatsSplits
     */
    month?: any;
    /**
     * 
     * @type {number}
     * @memberof PlayerStatsSplits
     */
    dayOfWeek?: any;
    /**
     * 
     * @type {DraftTeam}
     * @memberof PlayerStatsSplits
     */
    opponent?: any;
    /**
     * 
     * @type {PlayerStatsOpponentDivision}
     * @memberof PlayerStatsSplits
     */
    opponentDivision?: any;
    /**
     * 
     * @type {DivisionConference}
     * @memberof PlayerStatsSplits
     */
    opponentConference?: any;
}
