/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface PlayerStatsType
 */
export interface PlayerStatsType {
    /**
     * 
     * @type {string}
     * @memberof PlayerStatsType
     */
    displayName?: PlayerStatsTypeDisplayNameEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum PlayerStatsTypeDisplayNameEnum {
    ByDayOfWeek = 'byDayOfWeek',
    ByMonth = 'byMonth',
    GoalsByGameSituation = 'goalsByGameSituation',
    HomeAndAway = 'homeAndAway',
    OnPaceRegularSeason = 'onPaceRegularSeason',
    RegularSeasonStatRankings = 'regularSeasonStatRankings',
    StatsSingleSeason = 'statsSingleSeason',
    VsConference = 'vsConference',
    VsDivision = 'vsDivision',
    VsTeam = 'vsTeam',
    WinLoss = 'winLoss'
}

