/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ScheduleGameTeamsHomeLeagueRecord
 */
export interface ScheduleGameTeamsHomeLeagueRecord {
    /**
     * 
     * @type {number}
     * @memberof ScheduleGameTeamsHomeLeagueRecord
     */
    wins?: any;
    /**
     * 
     * @type {number}
     * @memberof ScheduleGameTeamsHomeLeagueRecord
     */
    losses?: any;
    /**
     * 
     * @type {number}
     * @memberof ScheduleGameTeamsHomeLeagueRecord
     */
    ot?: any;
    /**
     * 
     * @type {string}
     * @memberof ScheduleGameTeamsHomeLeagueRecord
     */
    type?: any;
}
