/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ScheduleGame
 */
export interface ScheduleGame {
    /**
     * 
     * @type {number}
     * @memberof ScheduleGame
     */
    gamePk?: any;
    /**
     * 
     * @type {string}
     * @memberof ScheduleGame
     */
    link?: any;
    /**
     * 
     * @type {string}
     * @memberof ScheduleGame
     */
    gameType?: any;
    /**
     * 
     * @type {string}
     * @memberof ScheduleGame
     */
    season?: any;
    /**
     * 
     * @type {Date}
     * @memberof ScheduleGame
     */
    gameDate?: any;
    /**
     * 
     * @type {GameGameDataStatus}
     * @memberof ScheduleGame
     */
    status?: any;
    /**
     * 
     * @type {ScheduleGameTeams}
     * @memberof ScheduleGame
     */
    teams?: any;
    /**
     * 
     * @type {GameLinescore}
     * @memberof ScheduleGame
     */
    linescore?: any;
    /**
     * 
     * @type {GameGameDataVenue}
     * @memberof ScheduleGame
     */
    venue?: any;
    /**
     * 
     * @type {Array&lt;ScheduleGameTickets&gt;}
     * @memberof ScheduleGame
     */
    tickets?: any;
    /**
     * 
     * @type {ScheduleGameContent}
     * @memberof ScheduleGame
     */
    content?: any;
}
