/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface StandingsTeamRecords
 */
export interface StandingsTeamRecords {
    /**
     * 
     * @type {PlayerCurrentTeam}
     * @memberof StandingsTeamRecords
     */
    team?: any;
    /**
     * 
     * @type {ScheduleGameTeamsHomeLeagueRecord}
     * @memberof StandingsTeamRecords
     */
    leagueRecord?: any;
    /**
     * 
     * @type {number}
     * @memberof StandingsTeamRecords
     */
    goalsAgainst?: any;
    /**
     * 
     * @type {number}
     * @memberof StandingsTeamRecords
     */
    goalsScored?: any;
    /**
     * 
     * @type {number}
     * @memberof StandingsTeamRecords
     */
    points?: any;
    /**
     * 
     * @type {string}
     * @memberof StandingsTeamRecords
     */
    divisionRank?: any;
    /**
     * 
     * @type {string}
     * @memberof StandingsTeamRecords
     */
    conferenceRank?: any;
    /**
     * 
     * @type {string}
     * @memberof StandingsTeamRecords
     */
    leagueRank?: any;
    /**
     * 
     * @type {string}
     * @memberof StandingsTeamRecords
     */
    wildCardRank?: any;
    /**
     * 
     * @type {number}
     * @memberof StandingsTeamRecords
     */
    row?: any;
    /**
     * 
     * @type {number}
     * @memberof StandingsTeamRecords
     */
    gamesPlayed?: any;
    /**
     * 
     * @type {StandingsStreak}
     * @memberof StandingsTeamRecords
     */
    streak?: any;
    /**
     * 
     * @type {Date}
     * @memberof StandingsTeamRecords
     */
    lastUpdated?: any;
}
