/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface StatTypesInner
 */
export interface StatTypesInner {
    /**
     * 
     * @type {string}
     * @memberof StatTypesInner
     */
    displayName?: StatTypesInnerDisplayNameEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum StatTypesInnerDisplayNameEnum {
    ByDayOfWeek = 'byDayOfWeek',
    ByDayOfWeekPlayoffs = 'byDayOfWeekPlayoffs',
    ByMonth = 'byMonth',
    ByMonthPlayoffs = 'byMonthPlayoffs',
    CareerPlayoffs = 'careerPlayoffs',
    CareerRegularSeason = 'careerRegularSeason',
    GameLog = 'gameLog',
    GoalsByGameSituation = 'goalsByGameSituation',
    GoalsByGameSituationPlayoffs = 'goalsByGameSituationPlayoffs',
    HomeAndAway = 'homeAndAway',
    HomeAndAwayPlayoffs = 'homeAndAwayPlayoffs',
    OnPaceRegularSeason = 'onPaceRegularSeason',
    PlayoffGameLog = 'playoffGameLog',
    PlayoffStatRankings = 'playoffStatRankings',
    RegularSeasonStatRankings = 'regularSeasonStatRankings',
    StatsSingleSeason = 'statsSingleSeason',
    StatsSingleSeasonPlayoffs = 'statsSingleSeasonPlayoffs',
    VsConference = 'vsConference',
    VsConferencePlayoffs = 'vsConferencePlayoffs',
    VsDivision = 'vsDivision',
    VsDivisionPlayoffs = 'vsDivisionPlayoffs',
    VsTeam = 'vsTeam',
    VsTeamPlayoffs = 'vsTeamPlayoffs',
    WinLoss = 'winLoss',
    WinLossPlayoffs = 'winLossPlayoffs',
    YearByYear = 'yearByYear',
    YearByYearPlayoffs = 'yearByYearPlayoffs',
    YearByYearPlayoffsRank = 'yearByYearPlayoffsRank',
    YearByYearRank = 'yearByYearRank'
}

