/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface TeamNextGameScheduleStatus
 */
export interface TeamNextGameScheduleStatus {
    /**
     * 
     * @type {string}
     * @memberof TeamNextGameScheduleStatus
     */
    abstractGameState?: TeamNextGameScheduleStatusAbstractGameStateEnum;
    /**
     * 
     * @type {string}
     * @memberof TeamNextGameScheduleStatus
     */
    codedGameState?: TeamNextGameScheduleStatusCodedGameStateEnum;
    /**
     * 
     * @type {string}
     * @memberof TeamNextGameScheduleStatus
     */
    detailedState?: TeamNextGameScheduleStatusDetailedStateEnum;
    /**
     * 
     * @type {string}
     * @memberof TeamNextGameScheduleStatus
     */
    statusCode?: TeamNextGameScheduleStatusStatusCodeEnum;
    /**
     * 
     * @type {boolean}
     * @memberof TeamNextGameScheduleStatus
     */
    startTimeTBD?: any;
}

/**
    * @export
    * @enum {string}
    */
export enum TeamNextGameScheduleStatusAbstractGameStateEnum {
    Live = 'Live',
    Preview = 'Preview'
}
/**
    * @export
    * @enum {string}
    */
export enum TeamNextGameScheduleStatusCodedGameStateEnum {
    _2 = '2',
    _3 = '3'
}
/**
    * @export
    * @enum {string}
    */
export enum TeamNextGameScheduleStatusDetailedStateEnum {
    InProgress = 'In Progress',
    PreGame = 'Pre-Game'
}
/**
    * @export
    * @enum {string}
    */
export enum TeamNextGameScheduleStatusStatusCodeEnum {
    _2 = '2',
    _3 = '3'
}

