/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Team
 */
export interface Team {
    /**
     * 
     * @type {number}
     * @memberof Team
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof Team
     */
    name?: any;
    /**
     * 
     * @type {string}
     * @memberof Team
     */
    link?: any;
    /**
     * 
     * @type {Venue}
     * @memberof Team
     */
    venue?: any;
    /**
     * 
     * @type {string}
     * @memberof Team
     */
    abbreviation?: any;
    /**
     * 
     * @type {string}
     * @memberof Team
     */
    triCode?: any;
    /**
     * 
     * @type {string}
     * @memberof Team
     */
    teamName?: any;
    /**
     * 
     * @type {string}
     * @memberof Team
     */
    locationName?: any;
    /**
     * 
     * @type {number}
     * @memberof Team
     */
    firstYearOfPlay?: any;
    /**
     * 
     * @type {StandingsDivision}
     * @memberof Team
     */
    division?: any;
    /**
     * 
     * @type {DivisionConference}
     * @memberof Team
     */
    conference?: any;
    /**
     * 
     * @type {Franchise}
     * @memberof Team
     */
    franchise?: any;
    /**
     * 
     * @type {TeamRoster}
     * @memberof Team
     */
    roster?: any;
    /**
     * 
     * @type {TeamNextGameSchedule}
     * @memberof Team
     */
    nextGameSchedule?: any;
    /**
     * 
     * @type {string}
     * @memberof Team
     */
    shortName?: any;
    /**
     * 
     * @type {string}
     * @memberof Team
     */
    officialSiteUrl?: any;
    /**
     * 
     * @type {number}
     * @memberof Team
     */
    franchiseId?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Team
     */
    active?: any;
}
