/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface TeamStatsStat
 */
export interface TeamStatsStat {
    /**
     * 
     * @type {number}
     * @memberof TeamStatsStat
     */
    gamesPlayed?: any;
    /**
     * 
     * @type {number}
     * @memberof TeamStatsStat
     */
    wins?: any;
    /**
     * 
     * @type {number}
     * @memberof TeamStatsStat
     */
    losses?: any;
    /**
     * 
     * @type {number}
     * @memberof TeamStatsStat
     */
    ot?: any;
    /**
     * 
     * @type {number}
     * @memberof TeamStatsStat
     */
    pts?: any;
    /**
     * 
     * @type {string}
     * @memberof TeamStatsStat
     */
    ptPctg?: any;
    /**
     * 
     * @type {number}
     * @memberof TeamStatsStat
     */
    goalsPerGame?: any;
    /**
     * 
     * @type {number}
     * @memberof TeamStatsStat
     */
    goalsAgainstPerGame?: any;
    /**
     * 
     * @type {number}
     * @memberof TeamStatsStat
     */
    evGGARatio?: any;
    /**
     * 
     * @type {string}
     * @memberof TeamStatsStat
     */
    powerPlayPercentage?: any;
    /**
     * 
     * @type {number}
     * @memberof TeamStatsStat
     */
    powerPlayGoals?: any;
    /**
     * 
     * @type {number}
     * @memberof TeamStatsStat
     */
    powerPlayGoalsAgainst?: any;
    /**
     * 
     * @type {number}
     * @memberof TeamStatsStat
     */
    powerPlayOpportunities?: any;
    /**
     * 
     * @type {string}
     * @memberof TeamStatsStat
     */
    penaltyKillPercentage?: any;
    /**
     * 
     * @type {number}
     * @memberof TeamStatsStat
     */
    shotsPerGame?: any;
    /**
     * 
     * @type {number}
     * @memberof TeamStatsStat
     */
    shotsAllowed?: any;
    /**
     * 
     * @type {number}
     * @memberof TeamStatsStat
     */
    winScoreFirst?: any;
    /**
     * 
     * @type {number}
     * @memberof TeamStatsStat
     */
    winOppScoreFirst?: any;
    /**
     * 
     * @type {number}
     * @memberof TeamStatsStat
     */
    winLeadFirstPer?: any;
    /**
     * 
     * @type {number}
     * @memberof TeamStatsStat
     */
    winLeadSecondPer?: any;
    /**
     * 
     * @type {number}
     * @memberof TeamStatsStat
     */
    winOutshootOpp?: any;
    /**
     * 
     * @type {number}
     * @memberof TeamStatsStat
     */
    winOutshotByOpp?: any;
    /**
     * 
     * @type {number}
     * @memberof TeamStatsStat
     */
    faceOffsTaken?: any;
    /**
     * 
     * @type {number}
     * @memberof TeamStatsStat
     */
    faceOffsWon?: any;
    /**
     * 
     * @type {number}
     * @memberof TeamStatsStat
     */
    faceOffsLost?: any;
    /**
     * 
     * @type {string}
     * @memberof TeamStatsStat
     */
    faceOffWinPercentage?: any;
    /**
     * 
     * @type {number}
     * @memberof TeamStatsStat
     */
    shootingPctg?: any;
    /**
     * 
     * @type {number}
     * @memberof TeamStatsStat
     */
    savePctg?: any;
}
