/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface TeamNextGameSchedule
 */
export interface TeamNextGameSchedule {
    /**
     * 
     * @type {number}
     * @memberof TeamNextGameSchedule
     */
    totalItems?: any;
    /**
     * 
     * @type {number}
     * @memberof TeamNextGameSchedule
     */
    totalEvents?: any;
    /**
     * 
     * @type {number}
     * @memberof TeamNextGameSchedule
     */
    totalGames?: any;
    /**
     * 
     * @type {number}
     * @memberof TeamNextGameSchedule
     */
    totalMatches?: any;
    /**
     * 
     * @type {Array&lt;TeamNextGameScheduleDates&gt;}
     * @memberof TeamNextGameSchedule
     */
    dates?: any;
}
