/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface TeamNextGameScheduleDates
 */
export interface TeamNextGameScheduleDates {
    /**
     * 
     * @type {string}
     * @memberof TeamNextGameScheduleDates
     */
    date?: any;
    /**
     * 
     * @type {number}
     * @memberof TeamNextGameScheduleDates
     */
    totalItems?: any;
    /**
     * 
     * @type {number}
     * @memberof TeamNextGameScheduleDates
     */
    totalEvents?: any;
    /**
     * 
     * @type {number}
     * @memberof TeamNextGameScheduleDates
     */
    totalGames?: any;
    /**
     * 
     * @type {number}
     * @memberof TeamNextGameScheduleDates
     */
    totalMatches?: any;
    /**
     * 
     * @type {Array&lt;TeamNextGameScheduleGames&gt;}
     * @memberof TeamNextGameScheduleDates
     */
    games?: any;
    /**
     * 
     * @type {Array&lt;any&gt;}
     * @memberof TeamNextGameScheduleDates
     */
    events?: any;
    /**
     * 
     * @type {Array&lt;any&gt;}
     * @memberof TeamNextGameScheduleDates
     */
    matches?: any;
}
