/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface TeamNextGameScheduleGames
 */
export interface TeamNextGameScheduleGames {
    /**
     * 
     * @type {number}
     * @memberof TeamNextGameScheduleGames
     */
    gamePk?: any;
    /**
     * 
     * @type {string}
     * @memberof TeamNextGameScheduleGames
     */
    link?: any;
    /**
     * 
     * @type {string}
     * @memberof TeamNextGameScheduleGames
     */
    gameType?: any;
    /**
     * 
     * @type {string}
     * @memberof TeamNextGameScheduleGames
     */
    season?: any;
    /**
     * 
     * @type {Date}
     * @memberof TeamNextGameScheduleGames
     */
    gameDate?: any;
    /**
     * 
     * @type {TeamNextGameScheduleStatus}
     * @memberof TeamNextGameScheduleGames
     */
    status?: any;
    /**
     * 
     * @type {TeamNextGameScheduleTeams}
     * @memberof TeamNextGameScheduleGames
     */
    teams?: any;
    /**
     * 
     * @type {GameGameDataVenue}
     * @memberof TeamNextGameScheduleGames
     */
    venue?: any;
    /**
     * 
     * @type {ScheduleGameContent}
     * @memberof TeamNextGameScheduleGames
     */
    content?: any;
}
