/* tslint:disable */
/* eslint-disable */
/**
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Venue
 */
export interface Venue {
    /**
     * 
     * @type {string}
     * @memberof Venue
     */
    name?: any;
    /**
     * 
     * @type {string}
     * @memberof Venue
     */
    link?: any;
    /**
     * 
     * @type {string}
     * @memberof Venue
     */
    city?: any;
    /**
     * 
     * @type {VenueTimeZone}
     * @memberof Venue
     */
    timeZone?: any;
}
